#!/usr/bin/env python3
"""Build driver for all IEUMUN guides; the Makefile calls it one step at a time.

    python3 scripts/guides.py list                 slugs, sources and output names
    python3 scripts/guides.py deps                 build/deps.mk + build/links/ (for make)
    python3 scripts/guides.py convert SLUG         SG_assets source -> guides/SLUG/
    python3 scripts/guides.py pdf SLUG             guides/SLUG/main.pdf (fresh LaTeX build)
    python3 scripts/guides.py publish SLUG         checks + copy to out/<COLOUR>/<name>.pdf
    python3 scripts/guides.py check [SLUG ...]     print the build checks again
    python3 scripts/guides.py preview SLUG [PAGE ...]   PNG pages in .preview/SLUG/
    python3 scripts/guides.py prune                remove PDFs in out/ that no config produces

Each guide is described by SG_config/<slug>.json (see GUIDES.md). Everything in
guides/<slug>/ is generated and is wiped on every conversion.
"""

from __future__ import annotations

import json
import os
import re
import shutil
import subprocess
import sys
import zipfile
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
CONFIG_DIR = ROOT / "SG_config"
BUILD = ROOT / "build"
OUT = ROOT / "out"
PREVIEW = ROOT / ".preview"
CATEGORIES = {"BLACK": "black", "RED": "red", "BLUE": "blue"}

sys.path.insert(0, str(ROOT / "scripts"))


def load(slug: str) -> dict:
    path = CONFIG_DIR / f"{slug}.json"
    if not path.exists():
        sys.exit(f"No config {path}")
    cfg = json.loads(path.read_text(encoding="utf-8"))
    cfg["slug"] = slug
    cfg["source_path"] = ROOT / cfg["source"]
    cfg["cover_path"] = ROOT / cfg["cover"] if cfg.get("cover") else None
    folder = cfg["source_path"].parent.name.upper()
    cfg.setdefault("category", CATEGORIES.get(folder, "black"))
    name = cfg["output"] if cfg["output"].endswith(".pdf") else cfg["output"] + ".pdf"
    cfg["out_path"] = OUT / name
    cfg["guide_dir"] = ROOT / "guides" / slug
    return cfg


def slugs() -> list[str]:
    return sorted(p.stem for p in CONFIG_DIR.glob("*.json"))


# ---------------------------------------------------------------------------

def cmd_list(_args):
    for s in slugs():
        cfg = load(s)
        print(f"{s:28s} {cfg['category']:6s} {cfg['source']}  ->  {cfg['out_path'].relative_to(ROOT)}")


def cmd_deps(_args):
    """Symlinks with plain names let make track sources whose names contain spaces or brackets."""
    links = BUILD / "links"
    links.mkdir(parents=True, exist_ok=True)
    lines = ["# Generated by scripts/guides.py deps -- do not edit.", ""]
    for s in slugs():
        cfg = load(s)
        prereqs = []
        for kind, path in (("src", cfg["source_path"]), ("cover", cfg["cover_path"])):
            if path is None:
                continue
            if not path.exists():
                sys.exit(f"{s}: {kind} file not found: {path}")
            link = links / f"{s}.{kind}"
            if link.is_symlink() or link.exists():
                link.unlink()
            link.symlink_to(path)
            prereqs.append(f"build/links/{s}.{kind}")
        lines.append(f"guides/{s}/main.tex: {' '.join(prereqs)}")
    (BUILD / "deps.mk").write_text("\n".join(lines) + "\n", encoding="utf-8")


def prepare_source(cfg: dict) -> Path:
    """Word sources are used as they are; real binary .doc files go through textutil first."""
    src = cfg["source_path"]
    if zipfile.is_zipfile(src):
        return src
    dest = BUILD / "src" / f"{cfg['slug']}.docx"
    dest.parent.mkdir(parents=True, exist_ok=True)
    subprocess.run(["textutil", "-convert", "docx", "-output", str(dest), str(src)], check=True)
    return dest


def apply_patches(cfg: dict):
    """Per-guide editorial fixes on the generated LaTeX; a patch that no longer matches is an error."""
    guide = cfg["guide_dir"]
    for i, patch in enumerate(cfg.get("patches", []), 1):
        files = sorted(guide.glob(patch.get("file", "content/*.tex")))
        hits = 0
        for f in files:
            text = f.read_text(encoding="utf-8")
            if patch.get("regex"):
                new, n = re.subn(patch["find"], patch["replace"], text, flags=re.S)
            else:
                n = text.count(patch["find"])
                new = text.replace(patch["find"], patch["replace"])
            if n:
                f.write_text(new, encoding="utf-8")
                hits += n
        if not hits:
            sys.exit(f"{cfg['slug']}: patch {i} did not match anything: {patch['find'][:80]!r}\n"
                     f"Update or remove it in SG_config/{cfg['slug']}.json.")


def cmd_convert(args):
    import docx2guide

    cfg = load(args[0])
    guide = cfg["guide_dir"]
    if guide.exists():
        shutil.rmtree(guide)
    guide.mkdir(parents=True)
    report = docx2guide.convert(prepare_source(cfg), guide, cfg, cfg["category"], cfg["cover_path"], True)
    apply_patches(cfg)
    print(f"[{cfg['slug']}] converted: {len(report['sections'])} sections, {report['images']} images, "
          f"{report['expected_footnotes']} footnotes")
    for w in report["warnings"]:
        print(f"[{cfg['slug']}] note: {w}")


def latex_errors(guide: Path) -> bool:
    log = guide / "main.log"
    if not log.exists():
        return True
    text = log.read_text(encoding="utf-8", errors="replace")
    return bool(re.search(r"^(!|\S+:\d+: )", text, re.M))


def cmd_pdf(args):
    import fcntl

    cfg = load(args[0])
    guide = cfg["guide_dir"]

    def build():
        # A fresh build keeps the short-page fixer deterministic: its levels only go up.
        for ext in ("aux", "bbl", "bcf", "blg", "fdb_latexmk", "fls", "log", "out", "run.xml", "toc"):
            (guide / f"main.{ext}").unlink(missing_ok=True)
        proc = subprocess.run(["latexmk", "-silent", "main.tex"], cwd=guide,
                              stdout=subprocess.DEVNULL, stderr=subprocess.STDOUT)
        return proc.returncode == 0 and (guide / "main.pdf").exists() and not latex_errors(guide)

    if not build():
        # Parallel LuaLaTeX runs share one font cache and very occasionally trip
        # over each other; the retry runs alone.
        BUILD.mkdir(exist_ok=True)
        with open(BUILD / "latex.lock", "w") as lock:
            fcntl.flock(lock, fcntl.LOCK_EX)
            ok = build()
        if not ok:
            sys.exit(f"[{cfg['slug']}] LaTeX build failed; see guides/{cfg['slug']}/main.log")
    os.utime(guide / "main.pdf")


def checks(cfg: dict) -> tuple[list[str], list[str]]:
    guide = cfg["guide_dir"]
    problems, info = [], []
    log_path = guide / "main.log"
    if not log_path.exists():
        return ["not built yet"], info
    log = log_path.read_text(encoding="utf-8", errors="replace")
    errors = [l for l in log.splitlines()
              if l.startswith("!") or re.match(r"^\S+:\d+: ", l) or re.search(r"\b\w+ Error:", l)]
    if errors:
        problems.append(f"{len(errors)} LaTeX errors, first: {errors[0]}")
    if re.search(r"There were undefined references|Reference `[^']+' on page \d+ undefined", log):
        problems.append("undefined references")
    missing = re.findall(r"File `([^']+)' not found", log)
    if missing:
        problems.append("missing files: " + ", ".join(sorted(set(missing))))
    short = re.findall(r"Section (\d+)\s+ends with a nearly empty page \(p\.~?(\d+)\)", log.replace("\n", " "))
    for sec, page in short:
        problems.append(f"section {sec} ends with a nearly empty page (p. {page})")
    import docx2guide

    report = json.loads((guide / "convert-report.json").read_text(encoding="utf-8"))
    written = "".join(p.read_text(encoding="utf-8") for p in sorted((guide / "content").glob("*.tex")))
    want = len(docx2guide.footnote_bodies(written))
    m = re.findall(r"IEUMUN footnotes: (\d+)", log)
    if m:
        got = int(m[-1])
        outside = report.get("notes_outside_guide", 0)
        extra = (f" ({outside} of them in pages before the guide starts, e.g. a draft copy; "
                 f"their text is in the guide)" if outside and not report.get("source_notes_missing") else "")
        (info if got == want else problems).append(
            f"footnotes: {got} in the PDF, {want} in the LaTeX, {report['source_notes']} notes in the source{extra}")
    if report.get("source_notes_missing"):
        problems.append(f"{len(report['source_notes_missing'])} source notes are not in the guide")
    overfull = [float(x) for x in re.findall(r"Overfull \\hbox \(([\d.]+)pt too wide\)", log)]
    bad = [x for x in overfull if x > 3]
    if bad:
        problems.append(f"{len(bad)} lines stick out into the margin (up to {max(bad):.0f}pt)")
    pages = subprocess.run(["pdfinfo", str(guide / "main.pdf")], capture_output=True, text=True).stdout
    pm = re.search(r"Pages:\s+(\d+)", pages)
    info.append(f"{pm.group(1) if pm else '?'} pages")
    for w in report["warnings"]:
        info.append("converter: " + w)
    return problems, info


def cmd_publish(args):
    cfg = load(args[0])
    problems, info = checks(cfg)
    lines = [f"[{cfg['slug']}] {x}" for x in info] + [f"[{cfg['slug']}] CHECK: {x}" for x in problems]
    reports = BUILD / "reports"
    reports.mkdir(parents=True, exist_ok=True)
    (reports / f"{cfg['slug']}.txt").write_text("\n".join(lines) + "\n", encoding="utf-8")
    print("\n".join(lines))
    cfg["out_path"].parent.mkdir(parents=True, exist_ok=True)
    shutil.copyfile(cfg["guide_dir"] / "main.pdf", cfg["out_path"])
    stamp = BUILD / "stamps" / f"{cfg['slug']}.published"
    stamp.parent.mkdir(parents=True, exist_ok=True)
    stamp.write_text(str(cfg["out_path"].relative_to(ROOT)) + "\n", encoding="utf-8")
    print(f"[{cfg['slug']}] -> {cfg['out_path'].relative_to(ROOT)}")


def cmd_check(args):
    status = 0
    for s in args or slugs():
        problems, info = checks(load(s))
        print(f"{s}: " + "; ".join(info[:2]))
        for p in problems:
            print(f"  CHECK: {p}")
            status = 1
        for i in info[2:]:
            print(f"  {i}")
    sys.exit(status)


def cmd_preview(args):
    cfg = load(args[0])
    pdf = cfg["guide_dir"] / "main.pdf"
    dest = PREVIEW / cfg["slug"]
    dest.mkdir(parents=True, exist_ok=True)
    pages = [int(p) for p in args[1:]]
    if not pages:
        subprocess.run(["pdftoppm", "-r", "40", "-png", str(pdf), str(dest / "p")], check=True)
    for p in pages:
        subprocess.run(["pdftoppm", "-r", "40", "-png", "-f", str(p), "-l", str(p), str(pdf), str(dest / "p")],
                       check=True)
    print(dest)


def cmd_prune(_args):
    wanted = {load(s)["out_path"] for s in slugs()}
    if not OUT.exists():
        return
    for f in OUT.rglob("*.pdf"):
        if f not in wanted:
            print(f"removing stale {f.relative_to(ROOT)}")
            f.unlink()
    for d in sorted((p for p in OUT.rglob("*") if p.is_dir()), reverse=True):
        if not any(d.iterdir()):
            d.rmdir()


COMMANDS = {
    "list": cmd_list, "deps": cmd_deps, "convert": cmd_convert, "pdf": cmd_pdf, "publish": cmd_publish,
    "check": cmd_check, "preview": cmd_preview, "prune": cmd_prune,
}

if __name__ == "__main__":
    if len(sys.argv) < 2 or sys.argv[1] not in COMMANDS:
        sys.exit(__doc__)
    COMMANDS[sys.argv[1]](sys.argv[2:])
